-- Boarding PIN: 4 digits generated by the server for every trip. Only the
-- passenger can read it; the driver must type it to start the trip.
-- Stored apart from trips so the driver's row access never exposes it.

create table if not exists public.trip_pins (
  trip_id   uuid primary key references public.trips (id) on delete cascade,
  pin       text not null check (pin ~ '^[0-9]{4}$'),
  attempts  integer not null default 0
);
alter table public.trip_pins enable row level security;
-- No policies: reachable only through the SECURITY DEFINER functions below.
revoke all on public.trip_pins from anon, authenticated;

create or replace function public.trip_pin_on_insert()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.trip_pins (trip_id, pin)
  values (new.id, lpad((floor(random() * 10000))::int::text, 4, '0'));
  return new;
end $$;
revoke execute on function public.trip_pin_on_insert() from public, anon, authenticated;

drop trigger if exists trips_boarding_pin on public.trips;
create trigger trips_boarding_pin after insert on public.trips
  for each row execute function public.trip_pin_on_insert();

-- Trips already open get a PIN too.
insert into public.trip_pins (trip_id, pin)
select id, lpad((floor(random() * 10000))::int::text, 4, '0')
  from public.trips
 where status in ('requested', 'accepted', 'arriving', 'in_progress')
on conflict do nothing;

-- Passenger reads their own PIN.
create or replace function public.my_trip_pin(p_trip uuid)
returns text language sql stable security definer set search_path = public as $$
  select p.pin
    from public.trip_pins p
    join public.trips t on t.id = p.trip_id
   where p.trip_id = p_trip and t.passenger_id = auth.uid();
$$;
revoke execute on function public.my_trip_pin(uuid) from public, anon;
grant execute on function public.my_trip_pin(uuid) to authenticated;

-- Starting the trip now requires the PIN (max 5 wrong attempts per trip).
drop function if exists public.advance_ride(uuid, trip_status);
create or replace function public.advance_ride(p_trip uuid, p_status trip_status, p_pin text default null)
returns public.trips language plpgsql security definer set search_path = public as $$
declare
  t   public.trips;
  pin public.trip_pins;
begin
  if p_status = 'in_progress' then
    select * into pin from public.trip_pins where trip_id = p_trip for update;
    if not exists (select 1 from public.trips where id = p_trip and driver_id = auth.uid()) then
      raise exception 'Cambio de estado no permitido';
    end if;
    if pin.trip_id is not null then
      if pin.attempts >= 5 then
        raise exception 'Demasiados intentos. Pide al pasajero que revise su PIN o contacta soporte';
      end if;
      if p_pin is distinct from pin.pin then
        update public.trip_pins set attempts = attempts + 1 where trip_id = p_trip;
        -- Return null (not raise) so the attempt counter is kept; the app shows "PIN incorrecto".
        return null;
      end if;
    end if;
  end if;

  update public.trips
     set status = p_status,
         started_at   = case when p_status = 'in_progress' then now() else started_at end,
         completed_at = case when p_status = 'completed' then now() else completed_at end
   where id = p_trip
     and driver_id = auth.uid()
     and (
       (status = 'accepted'    and p_status = 'arriving') or
       (status in ('accepted', 'arriving') and p_status = 'in_progress') or
       (status = 'in_progress' and p_status = 'completed')
     )
  returning * into t;
  if not found then raise exception 'Cambio de estado no permitido'; end if;
  return t;
end $$;
revoke execute on function public.advance_ride(uuid, trip_status, text) from public, anon;
grant execute on function public.advance_ride(uuid, trip_status, text) to authenticated;
